# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa35305db44324971fb241c2a5175a8fc1abeb093e3fe4d65a749176f2ad8e3cdb59678f20ddd7ecec18040e81440a8d0fed455250a0e7e8bc59672ed8798af

test:
  secret_key_base: 0da5e925d8de3c83b3aef7531ee9d7472e2d4427969acf2dd292b57b1a1477788f6f3497c6bc18dac5a28b9e25e426a21e6117aa22922ad4ddab4ddf20f2aad0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2eeadbcec0e77d7e0418584a0b8de5bc0ad18d2e9c3788abfb03509bc8b69e3ba0e1b9f026157a201ba41a133ed13cb00aa04f9cda27cdc52345496017e0bb4f
